# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ee431efc957f3007c3ed28e407c065cb317a19ed63a65751b0342a4ee677c50aacbe70367757489dcfefc484372d634a7d78833175ec9d447958ac29140efc

test:
  secret_key_base: 287ce63914488c7db910565d659d3c6f567e815505a9995d6bb59b057ffb9db07f181fc987b1399bd8452ecb1dc61a45e2cef7e9f39644ae30f18312e60a84e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
